version: "3.7"
services:
    app:
        build:
            args:
                user: imal
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: presenceapi
        container_name: presence-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - presenceapi

    db:
        image: mysql/mysql-server:8.0
        container_name: presence-api-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3360:3306
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - presenceapi

    nginx:
        image: nginx:alpine
        container_name: presence-api-nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - presenceapi

networks:
    presenceapi:
        driver: bridge
        ipam:
            config:
                - subnet: 172.50.0.0/24
